OnlineMarket/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineMarket.Helper;
using OnlineMarket.Models;
using PagedList.Core;

namespace OnlineMarket.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly MarketDbContext _context;
        public INotyfService _notyfService { get; }

        public AdminCategoriesController(MarketDbContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsCategories = _context.Categories.AsNoTracking().OrderByDescending(x => x.CategoryId);

            PagedList<Category> models = new PagedList<Category>(lsCategories, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(category.CategoryName) + extension;
                    category.Thumb = await Utilities.UploadFile(fThumb, @"category", image.ToLower());
                }
                if (string.IsNullOrEmpty(category.Thumb))
                    category.Thumb = "default.jpg";
                category.Alias = Utilities.SEOUrl(category.CategoryName);

                _context.Add(category);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới danh mục thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(category.CategoryName) + extension;
                        category.Thumb = await Utilities.UploadFile(fThumb, @"category", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(category.Thumb))
                        category.Thumb = "default.jpg";
                    category.Alias = Utilities.SEOUrl(category.CategoryName);
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật danh mục thành công");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'MarketDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa danh mục thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

OnlineMarket/Areas/Admin/Views/AdminCategories/Create.cshtml
@model OnlineMarket.Models.Category

@{
	ViewData["Title"] = "Tạo mới danh mục";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
	<link href="~/adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
	<link href="~/adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item">Home</a>
			<a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh sách danh mục</a>
			<span class="breadcrumb-item active">Tạo mới danh mục</span>
		</nav>
	</div>
</div>

<form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="page-header no-gutters has-tab">
		<h2>Tạo mới danh mục</h2>
		<div class="d-md-flex m-b-15 align-items-center justify-content-between">
			<div class="m-b-15">
				<button class="btn btn-primary">
					<span>Thêm danh mục</span>
				</button>
			</div>
		</div>
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin mô tả</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
			</li>
		</ul>
	</div>
	<div class="tab-content m-t-15">
		<div class="tab-pane fade show active" id="product-edit-basic">
			<div class="card">
				<div class="card-body">
					<div asp-validation-summary="All" class="text-danger"></div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productName">Tên danh mục</label>
						<input type="text" class="form-control" asp-for="CategoryName">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="Ordering">Sắp xếp</label>
						<input type="text" class="form-control" asp-for="Ordering">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
						<input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
						<span asp-validation-for="Thumb" class="text-danger"></span>
					</div>
					<div class="row">
						<div class="m-t-25">
							<div class="form-group d-flex align-items-center">
								<div class="switch m-r-10">
									<input type="checkbox" asp-for="Published" checked="">
									<label for="Active"></label>
								</div>
								<label>Public</label>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="product-edit-option">
			<div class="card">
				<div class="card-body">
					<div class="form-group">
						<label class="font-weight-semibold" for="productSize">Title</label>
						<input type="text" class="form-control" asp-for="Title">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productColors">MetaDesc</label>
						<input type="text" class="form-control" asp-for="MetaDesc">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productFit">MetaKey</label>
						<input type="text" class="form-control" asp-for="MetaKey">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
						<input type="text" class="form-control" asp-for="SchemaMarkup">
					</div>
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="product-edit-description">
			<div class="card">
				<div class="card-body">
					<textarea class="summernote" asp-for="Description"></textarea>
				</div>
			</div>
		</div>
	</div>
</form>

@section Scripts{
	<script src="~/adminassets/vendors/select2/select2.min.js"></script>
	<script src="~/adminassets/js/pages/e-commerce-product-edit.js"></script>
	<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
	<script src="~/adminassets/summernote/summernote-bs4.js"></script>

	<script>

		jQuery(document).ready(function() {
			$('.summernote').summernote({
				fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
				styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
				height: 200,
				minHeight: null,
				maxHeight: null,
				focus: true
			});
		});
	</script>
}

OnlineMarket/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model OnlineMarket.Models.Category

@{
	ViewData["Title"] = "Xác nhận xóa danh mục: " + Model.CategoryName;
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item">Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh sách danh mục</a>
			<span class="breadcrumb-item active">Xác nhận xóa danh mục: @Model.CategoryName</span>
		</nav>
	</div>
</div>

<div class="page-header no-gutters has-tab">
	<div class="d-md-flex m-b-15 align-items-center justify-content-between">
		<div class="media align-items-center m-b-15">
			<div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
				<img src="~/images/categories/@Model.Thumb" alt="@Model.Title">
			</div>
			<div class="m-l-15">
				<h4 class="m-b-0">@Model.CategoryName</h4>
				<p class="text-muted m-b-0">ID: @Model.CategoryId</p>
			</div>
		</div>

	</div>
	<h2 style="text-align: left;">Xác nhận xóa danh mục này?</h2>
	<ul class="nav nav-tabs">
		<li class="nav-item">
			<a class="nav-link active" data-toggle="tab" href="#product-overview">Overview</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#product-images">Ảnh đại diện</a>
		</li>
	</ul>
</div>

<div class="container-fluid">
	<div class="tab-content m-t-15">
		<div class="tab-pane fade active show" id="product-overview">
			<div class="card">
				<div class="card-body">
					<div class="table-responsive">
						<form asp-action="Delete" asp-route-id="@Model.CategoryId">
							<input type="hidden" asp-for="CategoryId" />
							<table class="product-info-table m-t-20">
								<tbody>
									<tr>
										<td>Tên danh mục:</td>
										<td class="text-dark font-weight-semibold">@Model.CategoryName</td>
									</tr>
									<tr>
										<td>Alias:</td>
										<td>@Model.Alias</td>
									</tr>
									<tr>
										<td>Trạng thái:</td>
										<td>
											<div class="checkbox">
												<input asp-for="Published" type="checkbox" />
												<label for="Published">Public</label>
											</div>
										</td>
									</tr>
									<tr>
										<div class="card">
											<div class="card-header">
												<h4 class="card-title">Thông tin mô tả</h4>
											</div>
											<div class="card-body">
												@Html.Raw(Model.Description)
											</div>
										</div>
									</tr>
									<tr>
										<td>Xác nhận xóa:</td>
										<td>
											<form asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@Model.CategoryId">
												<input type="hidden" asp-for="CategoryId" />
												<input type="submit" value="Xóa" class="btn btn-danger" />
												<a asp-action="Index" class="btn btn-primary btn-tone m-r-5">Quay lại danh sách</a>
											</form>
										</td>
									</tr>
								</tbody>
							</table>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="product-images">
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-md-3">
							<img class="img-fluid" src="~/images/categories/@Model.Thumb" alt="@Model.Title">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

OnlineMarket/Areas/Admin/Views/AdminCategories/Details.cshtml
@model OnlineMarket.Models.Category

@{
	ViewData["Title"] = "Thông tin danh mục: " + Model.CategoryName;
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item">Trang chủ</a>
			<a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh sách danh mục</a>
			<span class="breadcrumb-item active">Thông tin danh mục: @Model.CategoryName</span>
		</nav>
	</div>
</div>

<div class="page-header no-gutters has-tab">
	<div class="d-md-flex m-b-15 align-items-center justify-content-between">
		<div class="media align-items-center m-b-15">
			<div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
				<img src="~/images/categories/@Model.Thumb" alt="@Model.Title">
			</div>
			<div class="m-l-15">
				<h4 class="m-b-0">@Model.CategoryName</h4>
				<p class="text-muted m-b-0">ID: @Model.CategoryId</p>
			</div>
		</div>
	</div>
	<ul class="nav nav-tabs">
		<li class="nav-item">
			<a class="nav-link active" data-toggle="tab" href="#product-overview">Overview</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="tab" href="#product-images">Ảnh đại diện</a>
		</li>
	</ul>
</div>
<div class="container-fluid">
	<div class="tab-content m-t-15">
		<div class="tab-pane fade active show" id="product-overview">
			<div class="card">
				<div class="card-body">
					<h2 style="text-align: left; margin-top: 20px; margin-left: 10px;">Thông tin danh mục: @Model.CategoryName</h2>
					<div class="table-responsive">
						<table class="product-info-table m-t-20">
							<tbody>
								<tr>
									<td>Tên danh mục</td>
									<td class="text-dark font-weight-semibold">@Model.CategoryName</td>
								</tr>
								<tr>
									<td>Alias:</td>
									<td>@Model.Alias</td>
								</tr>
								<tr>
									<td>Trạng thái:</td>
									<td>
										<div class="checkbox">
											<input asp-for="Published" type="checkbox" />
											<label for="Published">Public</label>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="card">
				<div class="card-header">
					<h4 class="card-title">Thông tin mô tả</h4>
				</div>
				<div class="card-body">
					@Html.Raw(Model.Description)
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="product-images">
			<div class="card">
				<div class="card-body">
					<div class="row">
						<div class="col-md-3">
							<img class="img-fluid" src="~/images/categories/@Model.Thumb" alt="@Model.Title">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

OnlineMarket/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model OnlineMarket.Models.Category

@{
	ViewData["Title"] = "Chỉnh sửa danh mục";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
	<link href="~/adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
	<link href="~/adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item">Home</a>
			<a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh sách danh mục</a>
			<span class="breadcrumb-item active">Chỉnh sửa danh mục</span>
		</nav>
	</div>
</div>

<form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CategoryId" method="post" enctype="multipart/form-data">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<input type="hidden" asp-for="CategoryId"></input>
	<input type="hidden" asp-for="Thumb"></input>

	<div class="page-header no-gutters has-tab">
		<h2>Chỉnh sửa danh mục</h2>
		<div class="d-md-flex m-b-15 align-items-center justify-content-between">
			<div class="m-b-15">
				<button class="btn btn-primary">
					<span>Lưu thay đổi</span>
				</button>
			</div>
		</div>
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin mô tả</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
			</li>
		</ul>
	</div>
	<div class="tab-content m-t-15">
		<div class="tab-pane fade show active" id="product-edit-basic">
			<div class="card">
				<div class="card-body">
					<div asp-validation-summary="All" class="text-danger"></div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productName">Tên danh mục</label>
						<input type="text" class="form-control" asp-for="CategoryName">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="Ordering">Sắp xếp</label>
						<input type="text" class="form-control" asp-for="Ordering">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productBrand">Ảnh đại diện</label>
						<input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
						<span asp-validation-for="Thumb" class="text-danger"></span>
					</div>
					<div class="row">
						<div class="m-t-25">
							<div class="form-group d-flex align-items-center">
								<div class="switch m-r-10">
									<input type="checkbox" asp-for="Published" checked="">
									<label for="Active"></label>
								</div>
								<label>Public</label>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="product-edit-option">
			<div class="card">
				<div class="card-body">
					<div class="form-group">
						<label class="font-weight-semibold" for="productSize">Title</label>
						<input type="text" class="form-control" asp-for="Title">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productColors">MetaDesc</label>
						<input type="text" class="form-control" asp-for="MetaDesc">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productFit">MetaKey</label>
						<input type="text" class="form-control" asp-for="MetaKey">
					</div>
					<div class="form-group">
						<label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
						<input type="text" class="form-control" asp-for="SchemaMarkup">
					</div>
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="product-edit-description">
			<div class="card">
				<div class="card-body">
					<textarea class="summernote" asp-for="Description"></textarea>
				</div>
			</div>
		</div>
	</div>
</form>

@section Scripts{
	<script src="~/adminassets/vendors/select2/select2.min.js"></script>
	<script src="~/adminassets/js/pages/e-commerce-product-edit.js"></script>
	<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
	<script src="~/adminassets/summernote/summernote-bs4.js"></script>

	<script>

		jQuery(document).ready(function() {
			$('.summernote').summernote({
				fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
				styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
				height: 200,
				minHeight: null,
				maxHeight: null,
				focus: true
			});
		});
	</script>
}

OnlineMarket/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<OnlineMarket.Models.Category>

@{
	int CurrentPage = ViewBag.CurrentPage;
	ViewData["Title"] = "Quản lý danh mục - Trang " + CurrentPage;
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
	<div class="header-sub-title">
		<nav class="breadcrumb breadcrumb-dash">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item">Home</a>
			<span class="breadcrumb-item active">Danh sách danh mục</span>
		</nav>
	</div>
</div>

<div class="card">
	<h2 style="text-align: left; margin-top: 20px; margin-left: 20px;">Quản lý danh mục</h2>
	<div class="card-body">
		<div class="row m-b-30">
			<div class="col-lg-4 text-left">
				<a class="btn btn-primary" asp-controller="AdminCategories" asp-action="Create"><span>Thêm danh mục</span></a>
			</div>
			<div class="table-responsive">
				<table class="table table-hover e-commerce-table">
					<thead>
						<tr>
							<th>ID</th>
							<th>Danh mục</th>
							<th>Sắp xếp</th>
							<th>Trạng thái</th>
							<th>#</th>
						</tr>
					</thead>
					<tbody>
						@if (Model != null)
						{
							foreach (var item in Model)
							{
								string url = $"/{item.Alias}";
								<tr>
									<td>@item.CategoryId</td>
									<td>@item.CategoryName</td>
									<td>@item.Ordering</td>
									<td>
										@if (item.Published == true)
										{
											<div class="d-flex align-items-center">
												<div class="badge badge-success badge-dot m-r-10"></div>
												<div>Public</div>
											</div>
										}
										else
										{
											<div class="d-flex align-items-center">
												<div class="badge badge-success badge-dot m-r-10"></div>
												<div>Non-public</div>
											</div>
										}
									</td>
									<td>
										<a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.CategoryId">Chi tiết</a>
										<a class="btn btn-info btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.CategoryId">Sửa</a>
										<a class="btn btn-danger btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.CategoryId">Xóa</a>
									</td>
								</tr>
							}
						}
					</tbody>
				</table>
				<div aria-label="Page navigation example">
					<ul class="pagination">
						<pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCategories" asp-route-CategoryID="@ViewBag.CurrentCategoryID" asp-action="Index" />
					</ul>
				</div>
			</div>
		</div>
	</div>